### ISSUE TITLE
[SOLVED] Cannot get PyYapf to run in Sublime Text

### ISSUE THREAD

**Issue by LetsZiggy** [jason-kane/PyYapf#50]
Hi,
- I'm working in a virtual env, `python -m venv venv --system-site-packages`
- I cannot get PyYapf to run in Sublime Text
- I can get `yapf` to run in the CLI
- I have `[yapf]` section based on `--style-help` in `setup.cfg`

venv:
```
python --version
Python 3.8.1

yapf --version
yapf 0.29.0

subl --version
Sublime Text Build 3211
```

Error:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/shafiq/.config/sublime-text-3/Installed Packages/PyYapf Python Formatter.sublime-package/PyYapf.py", line 490, in run
  File "/home/shafiq/.config/sublime-text-3/Installed Packages/PyYapf Python Formatter.sublime-package/PyYapf.py", line 265, in format
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1351, in _execute_child
IndexError: list index out of range
```

PyYapf user settings:
```
{
  "on_save": true
}
```

Folder structure:
```
[project_root]
  |_.git/
  |_django/
  |  |_venv/
  |  |_setup.cfg
  |  |_...
  |_editor.sublime-project
  |_...
```
Edited:
- 2020-02-29
  - Added `--system-site-packages` to `python -m venv venv`
  - Changed `[style]` to `[yapf]`
    - I've restarted Sublime Text after I've found this mistake but still same error

**Comment by jason-kane** [comment]
Weird, I'll try and reproduce the issue.  Looks like Linux?

**Comment by LetsZiggy** [comment]
Hi @jason-kane,
thanks for taking some time helping me out. I'm running Manjaro Cinnamon. I've updated PyYapf settings as adviced.

Error:
```
PyYapf: Encoding is 'UTF-8'
PyYapf: Formatting selection (0, 165)
PyYapf: Detected indent ''
PyYapf: Running [] in /home/shafiq/code/poll-application/django/polls
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/shafiq/.config/sublime-text-3/Installed Packages/PyYapf Python Formatter.sublime-package/PyYapf.py", line 490, in run
  File "/home/shafiq/.config/sublime-text-3/Installed Packages/PyYapf Python Formatter.sublime-package/PyYapf.py", line 265, in format
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1351, in _execute_child
IndexError: list index out of range
```

**Comment by jason-kane** [comment]
ok, there it is.  "PyYapf: Running [] in /home/shafiq/code/poll-application/django/polls" which leads to the IndexError.

The workaround is to set:
{
    "yapf_command": "/usr/bin/yapf"
}

ie: whatever cli command already works for you.

It is a little odd that pyyapf couldn't find the yapf executable, it's usually pretty good at that.

**Comment by LetsZiggy** [comment]
@jason-kane 
does it take Sublime Text variables, eg $folder, or arrays?

**Comment by jason-kane** [comment]
Whatever you put in there will be split to a list and fed to popen.  Popen is generally happiest with an absolute path.  I know, irritating to change the plugin config for each project.  It doesn't take sublime variables, that would be a good thing to add.

**Comment by jason-kane** [comment]
hehe, wow, didn't expect that to work.
